#!/bin/bash
array=[]
print ("Enter length of Array")
length=int(input())
print ("Enter values:")
for i in range(length):
	x=int(input())
	array.append(x)

if ( length % 2 ==0 ):
        index = int((length/2))
        
        median = (array[index-1] + array[index])/2
        
else:	
	median=array[(length-1)/2]

print ("Median is %d:",median)
